### ISSUE TITLE
Add Instructions for Finding GIFs

### ISSUE THREAD

**Issue by M0nica** [M0nica/httriri#12]
- Update the readme to include resources and instructions for finding or creating GIFs.

**Comment by Ruth-ikegah** [comment]
Can I take this up @M0nica

**Comment by M0nica** [comment]
@Ruth-ikegah there was a PR merged that addressed how to create GIFs. Do you want to update the README with tips for finding GIFs?

**Comment by Ruth-ikegah** [comment]
Yes, that will be nice. can I go ahead?

**Comment by M0nica** [comment]
@Ruth-ikegah yes, thanks!
