### ISSUE TITLE
Automate Optimizing GIFs

### ISSUE THREAD

**Issue by M0nica** [M0nica/httriri#20]
I tried to add the crush pics github action to process images but it doesn't seem to be working as expected:
- https://github.com/M0nica/httriri/blob/main/.github/workflow/crush-pics.yml 
- https://github.com/crush-pics/crush-pics-github-action

The repository needs some way of automating the optimization of GIFs that works retroactively for GIFs that were already added as well as runs every time new images are added.

**Comment by aaryanporwal** [comment]
You can use [imgbot](https://github.com/marketplace/imgbot), it can automatically optimise all gifs on every pr!

**Comment by M0nica** [comment]
@aaryanporwal Thank you for that recommendation! It looks promising. https://github.com/M0nica/httriri/pull/33
