### ISSUE TITLE
Invalid footer link [Add a status code]

### ISSUE THREAD

**Issue by AkashRajpurohit** [M0nica/httriri#61]
The current link in footer points to [https://github.com/M0nica/httriri#adding-a-new-status-code/](https://github.com/M0nica/httriri#adding-a-new-status-code/) rather it should be [https://github.com/M0nica/httriri#adding-a-new-status-code](https://github.com/M0nica/httriri#adding-a-new-status-code) _Without the trailing slash_

With the trailing slash it does not scroll to the exact place it is intended to go when redirected to github.

**Comment by M0nica** [comment]
@AkashRajpurohit thanks for flagging this. Are you interested in submitting the fix?

**Comment by AkashRajpurohit** [comment]
@M0nica Sure, although if someone else wants to take the opportunity to learn how to send PRs to open source then i'll be happy to assist him/her for this.

If no one else is taking, i'll send the PR 😄 

Is that okay with you?

**Comment by touchSarcasticSad** [comment]
Is it fine if i fix the issue ? I had added the link originally and i kinda messed up it seems😅

**Comment by M0nica** [comment]
This issue is still available however I defer to @AkashRajpurohit since they commented first so it would be great if you all could coordinate amongst yourselves.

**Comment by touchSarcasticSad** [comment]
Ok no problem @AkashRajpurohit  can do this fix. I'll try working on the unit tests

**Comment by AkashRajpurohit** [comment]
Cool, will send the fix PR.
