### ISSUE TITLE
Set Up Prettier

### ISSUE THREAD

**Issue by M0nica** [M0nica/httriri#76]
Right now there are misc. formatting changes when someone commits to this repo. Ideally Prettier would be set up and linting would be enforced with husky pre-commit hook and/or checked and fixed by GitHub Action CI 

- https://prettier.io/
https://github.com/typicode/husky

**Comment by jabbar86** [comment]
@M0nica I would like to work on this.

**Comment by jabbar86** [comment]
@M0nica thank you. Can you please close this PR. So others cant waste time in rebuilding the code. Looking forward to work on other issues :)
